# azure-pipelines.yml

parameters:
  - name: SiteToBuild
    displayName: 'Choose the site to build'
    type: string
    default: 'site1'
    values:
      - 'site1'
      - 'site2'

trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildSite1
    displayName: Build Site 1
    condition: eq('${{ parameters.SiteToBuild }}', 'site1')
    jobs:
      - job: BuildSite1Job
        displayName: Build Site 1
        steps:
          - script: |
              echo "Building Site 1..."
              # Mettez ici les commandes pour construire le site web 1
            displayName: "Build Site 1"

  - stage: BuildSite2
    displayName: Build Site 2
    condition: eq('${{ parameters.SiteToBuild }}', 'site2')
    jobs:
      - job: BuildSite2Job
        displayName: Build Site 2
        steps:
          - script: |
              echo "Building Site 2..."
              # Mettez ici les commandes pour construire le site web 2
            displayName: "Build Site 2"
