parameters:
  - name: SiteToBuild
    displayName: 'Choose the site to build'
    type: string
    default: 'site1'
    values:
      - 'site1'
      - 'site2'

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build Websites
    jobs:
      - job: BuildSite
        displayName: Build Chosen Site
        steps:
          - script: |
              if [ "${{ parameters.SiteToBuild }}" == "site1" ]; then
                echo "Building Site 1..."
                displayName: site1
                # Mettez ici les commandes pour construire le site web 1
              elif [ "${{ parameters.SiteToBuild }}" == "site2" ]; then
                echo "Building Site 2..."
                displayName: site2
                # Mettez ici les commandes pour construire le site web 2
              else
                echo "Invalid choice. Exiting..."
                exit 1
              fi
            displayName: "Build Chosen Site"