# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build Websites
    jobs:
      - job: ChooseSiteToBuild
        displayName: Choose Site to Build
        steps:
          - script: |
              echo "Which site do you want to build?"
              echo "1. Site 1"
              echo "2. Site 2"
              read -p "Enter the site number: " SITE_NUMBER
              if [ "$SITE_NUMBER" == "1" ]; then
                echo "Building Site 1..."
                # Mettez ici les commandes pour construire le site web 1
              elif [ "$SITE_NUMBER" == "2" ]; then
                echo "Building Site 2..."
                # Mettez ici les commandes pour construire le site web 2
              else
                echo "Invalid choice. Exiting..."
                exit 1
              fi
            displayName: "Choose Site and Build"
